const rooms = [
  {
    id: 1,
    name: 'Standard Room',
    info: 'MAX 1 GUEST/1 BED SPACE',
    price: 20000,
    description: 'Indulge in comfort and convenience in our Standard Room at Brisbane Hotel & Suites. Designed with your utmost satisfaction in mind, our Standard Room offers a cozy retreat for your stay.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X4 Cozy Bed',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',

    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
  {
    id: 2,
    name: 'Deluxe Room',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: 30000,
    description: 'Experience unparalleled comfort and sophistication in our Deluxe Room at Brisbane Hotel & Suites. Designed to exceed your expectations, our Deluxe Room offers a luxurious retreat for your stay.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
  {
    id: 3,
    name: 'Executive Room',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: 40000,
    description: 'Welcome to the epitome of refinement and comfort at Brisbane Hotel & Suites. Our Executive Room offers an exclusive sanctuary where every detail is meticulously crafted to exceed your expectations.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
  {
    id: 4,
    name: 'Executive Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: 50000,
    description: 'Experience the pinnacle of luxury and sophistication in our Executive Suite at Brisbane Hotel & Suites. It was designed to surpass your every expectation. Our Executive Suite offers a lavish retreat for you.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '42-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
  {
    id: 5,
    name: 'Royal Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: 60000,
    description: 'Welcome to an exquisite realm of luxury and grandeur at Brisbane Hotel & Suites. Our Royal Suite embodies opulence and sophistication, offering an unparalleled retreat for the most discerning guests.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '42-inch TV',
      '6X7 King-Size Bed',
      'Royal Sofa',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
  {
    id: 6,
    name: 'Double Royal Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: 80000,
    description: 'Step into a world of unparalleled luxury and sophistication with our Double Royal Suites. Designed to exceed your expectations, these suites offer a lavish retreat for those seeking the ultimate indulgence.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '53-inch TV',
      '6X7 King-Size Double Bed',
      'Royal Sofa',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255690/brisbane/bedroom_n4qlzc.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255692/brisbane/room_one_gbqqaq.jpg',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_scale,w_500/f_auto,q_auto:eco/v1708255694/brisbane/walky_huxhxf.jpg',
    ],
  },
];

export default rooms;
