const rooms = [
  {
    id: 1,
    name: 'Standard Room',
    info: 'MAX 1 GUEST/1 BED SPACE',
    price: '20,000',
    description: 'Indulge in comfort and convenience in our Standard Room at Brisbane Hotel & Suites. Designed with your utmost satisfaction in mind, our Standard Room offers a cozy retreat for your stay.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X4 Cozy Bed',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',

    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/v1709560631/sd_two_zhndzt.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_fill,w_1000,h_1000/v1709560631/sd_two_zhndzt.webp',
      '',
    ],
  },
  {
    id: 2,
    name: 'Deluxe Room',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: '30,000',
    description: 'Experience unparalleled comfort and sophistication in our Deluxe Room at Brisbane Hotel & Suites. Designed to exceed your expectations, our Deluxe Room offers a luxurious retreat for your stay.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_fill,w_500,h_400,e_improve,e_sharpen/v1709560644/roy_one_fqegqe.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/t_web asset/v1709560644/roy_two_vdzjat.webp',
    ],
  },
  {
    id: 3,
    name: 'Executive Room',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: '40,000',
    description: 'Welcome to the epitome of refinement and comfort at Brisbane Hotel & Suites. Our Executive Room offers an exclusive sanctuary where every detail is meticulously crafted to exceed your expectations.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '32-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/t_web asset/v1709560643/exec_one_sdffwq.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/t_web asset/v1709560625/exec_two_piijtr.webp',
    ],
  },
  {
    id: 4,
    name: 'Executive Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: '50,000',
    description: 'Experience the pinnacle of luxury and sophistication in our Executive Suite at Brisbane Hotel & Suites. It was designed to surpass your every expectation. Our Executive Suite offers a lavish retreat for you.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '42-inch TV',
      '6X6 Spacious Bed',
      'Cozy-Seating',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/v1709560641/exec_suite_one_q2id0n.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/t_web asset/v1709560638/exec_suite_two_ncmjma.webp',
    ],
  },
  {
    id: 5,
    name: 'Royal Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: '60,000',
    description: 'Welcome to an exquisite realm of luxury and grandeur at Brisbane Hotel & Suites. Our Royal Suite embodies opulence and sophistication, offering an unparalleled retreat for the most discerning guests.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '42-inch TV',
      '6X7 King-Size Bed',
      'Royal Sofa',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_fill,w_500,h_400,e_improve,e_sharpen/v1709560644/roy_one_fqegqe.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/t_web asset/v1709560644/roy_two_vdzjat.webp',
    ],
  },
  {
    id: 6,
    name: 'Presidential Suite',
    info: 'MAX 2 GUESTS/2 BED SPACES',
    price: '80,000',
    description: 'Step into a world of unparalleled luxury and sophistication with our Double Royal Suites. Designed to exceed your expectations, these suites offer a lavish retreat for those seeking the ultimate indulgence.',
    features: [
      'Complimentary Wi-Fi',
      'Delicious Breakfast',
      'Toiletries',
      '53-inch TV',
      '6X7 King-Size Double Bed',
      'Royal Sofa',
      '24/7 Room Service',
      'Access to Swimming Pool',
      'Free Parking',
    ],
    available: true,
    image: [
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/e_improve/v1709560643/pres_three_jb8nsb.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/c_crop,w_3024,h_4032,x_0,y_0,e_improve,e_sharpen/v1709560640/pres_two_ouz9tj.webp',
      'https://res.cloudinary.com/dn1ko8lbn/image/upload/e_sharpen/v1709560643/pres_three_jb8nsb.webp',
    ],
  },
];

export default rooms;
